services:
  # PHP FPM Service
  php:
    image: wodby/php:latest
    volumes:
      - './:/var/www/html'

# Nginx Service
  nginx:
    image: nginx:latest
    ports:
      - 88:80
    links:
      - 'php'
    volumes:
      - './:/var/www/html'
      - './docker/nginx:/etc/nginx/conf.d'
    depends_on:
      - php
  # Maria DB Service
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: R00Tp@ss
      MYSQL_DATABASE: m3prog_db
      MYSQL_USER: m3prog_user
      MYSQL_PASSWORD: m3prog_pass
    ports:
      - 3306:3306
  # phpmyadmin in an external image
    phpmyadmin:
      image: phpmyadmin:latest
      ports:
        - 8080:80
      environment:
        PMA_HOST: mariadb
        PMA_USER: m3prog_user
        PMA_PASSWORD: m3prog_pass
      depends_on:
        - mariadb
  